### ISSUE TITLE
Different results from the same sample with different methods of inputs

### ISSUE THREAD

**Issue by ZebinWen** [ImXman/MACA#1]
Hello,
When I integrated 8 samples into one Seurat object, and I extracted the whole raw count and put it into maca, I got the result like this:
![image](https://user-images.githubusercontent.com/78528508/148176317-a2304a99-7da0-4e9d-98d2-c794afa0db2d.png)
After that, I extracted each raw count from each sample, and do maca one by one, then saved the results. But when I put the result back in the integrated Seurat object, I found that this two results was different: 
![image](https://user-images.githubusercontent.com/78528508/148178803-a7e52302-0c0e-495e-a963-1c7f99e86df1.png)
Therefore, I am wondering that if it's because the different data inputs bring different niose which cause different computing process, and that if different methods of inputs generate different results, then which method should I choose?

Thanks a lot!

**Comment by ImXman** [comment]
Visually looking at these two figures, I couldn’t find a dramatic difference between these two. I would suggest you can use ARI and NMI to measure how much difference between two results.

One key step in MACA is clustering. Therefore, annotation of one single cell would be affected what other cells it is cluster with. I guess if you process samples as whole or samples one by one, the clustering process will be different. It’s probably the reason you got the different outcomes.

**Comment by ZebinWen** [comment]
Thank you so much for the quick reply and your suggestions! I will learn ARI and NMI first and then measure the differences. 

The point that I consider there is difference between this two results is that small purple cluster (whole: more quantity; one by one: less quantity). However, this 8 samples are all healthy mice. I am thinking if I process samples under different treatments or from different batches as a whole, would batch effects influenced the clustering and cause the results to be inaccurate? So from this perspective, maybe I should process samples one by one when I am annotating celltypes for samples from different batches?

Thanks a lot!

**Comment by ImXman** [comment]
I would process the same sample but different batches as one whole data. MACA is not affected by batch effects much, at least based on our observation.

**Comment by ZebinWen** [comment]
Thank you so much for your patience! It really help me have a deeper insight into MACA, an useful tool for celltype annotation. Hope it can be promoted and well maintained continuously, and hope that you can become Wolverine as soon as possible. :grin:

Best wishes!
